image: python:3.9

django_tests:
    tags:
        - docker
    script:
        - pip3 install opencv-python-headless
        - pip3 install -r backend/requirements.txt

        - python3 backend/manage.py makemigrations
        - python3 backend/manage.py migrate
        - python3 backend/manage.py check

        - python3 backend/manage.py test
    
    only:
        - developer 
