image: python:3.9

django_tests:
    tags:
        - docker
    script:
        - sudo apt-get update
        - sudo apt-get install ffmpeg libsm6 libxext6  -y  
        - pip3 install opencv-python
        - pip3 install -r backend/requirements.txt

        - python3 backend/manage.py makemigrations
        - python3 backend/manage.py migrate
        - python3 backend/manage.py check

        - python3 backend/manage.py test
    
    only:
        - developer 
