image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - echo "Setting up venv"
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - echo "Installing requirements"
    - pip3 install -r backend/requirements.txt
    - pip3 install opencv-python-headless  

django_tests:
    stage: test
    tags:
        - docker
    script:
        - echo "Migrating Django database"
        - python3 backend/manage.py makemigrations
        - python3 backend/manage.py migrate
        - python3 backend/manage.py check

        - echo "Executing Django tests"
        - python3 backend/manage.py test backend/
    only:
        - developer 

black:
    stage: test
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
    - black --check --verbose -- .
    only:
        - developer




