image: python:latest

django_tests:
    stage: test
    tags:
        - docker
    script:
        - echo "Installing requirements"
        - pip3 install -r backend/requirements.txt
        - pip3 install opencv-python-headless  

        - echo "Migrating Django database"
        - python3 backend/manage.py makemigrations
        - python3 backend/manage.py migrate
        - python3 backend/manage.py check

        - echo "Executing Django tests"
        - python3 backend/manage.py test backend/
    only:
        - developer 

black:
    stage: test
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --verbose -- .
    only:
        - developer