# Generated by Django 3.1.7 on 2022-02-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_HTML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Url_PDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('pdf_path', models.FilePathField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_PDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.IntegerField()),
                ('file_path', models.FilePathField(default=None)),
                ('pdf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamline.url_pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Table_HTML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FilePathField(default=None)),
                ('html_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamline.url_html')),
            ],
        ),
    ]
