# Generated by Django 3.1.7 on 2022-02-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url_table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Id', models.IntegerField()),
                ('csv_path', models.FilePathField(default=None, null=True)),
                ('Url_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamline.url_table')),
            ],
        ),
    ]
