# Generated by Django 3.1.7 on 2022-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='csv_path',
            field=models.FilePathField(default=None),
        ),
    ]
