# Generated by Django 3.1.7 on 2022-02-16 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streamline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_html',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='url_pdf',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
